Do nothing if device is not an SD card

diff --git a/utils/udev/sdremoved b/utils/udev/sdremoved
--- a/utils/udev/sdremoved
+++ b/utils/udev/sdremoved
@@ -1,5 +1,12 @@
 #!/bin/bash
 
+# Must be 1
+if [ "$ID_DRIVE_FLASH_SD" != "1" ]
+then
+  echo "Device is not a SD Card."
+  exit 1 # Exit silently.
+fi
+
 if [ -z "$(who)" ]
 then
    shutdown -P
